import assert from 'node:assert/strict';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import { parseFrontMatter, slugify, renderMarkdown, sanitizeHtml, excerpt, readingMinutes } from '../scripts/build-blog.mjs';

const read = file => readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
const exists = file => existsSync(new URL(`../${file}`, import.meta.url));

test('front matter parser handles scalars, inline lists, dash lists, and quotes', () => {
  const { meta, body } = parseFrontMatter(`---\ntitle: "Hello: world"\ndate: 2026-10-08\ntags: [A, "B C", d]\nseries:\n  - one\n  - two\ndraft: false\n---\n# Body\ntext`);
  assert.equal(meta.title, 'Hello: world');
  assert.equal(meta.date, '2026-10-08');
  assert.deepEqual(meta.tags, ['A', 'B C', 'd']);
  assert.deepEqual(meta.series, ['one', 'two']);
  assert.equal(meta.draft, false);
  assert.equal(body.trim(), '# Body\ntext');
  assert.deepEqual(parseFrontMatter('no front matter').meta, {});
});

test('slugify keeps Korean and ASCII, drops punctuation', () => {
  assert.equal(slugify('Redshift Datashare 운영 메모!'), 'redshift-datashare-운영-메모');
  assert.equal(slugify('  Hello__World  '), 'hello-world');
});

test('markdown renders headings with ids, highlighted code, external links, and lazy images', () => {
  const { html, headings } = renderMarkdown('## 섹션 하나\n\n```python\nprint("x")\n```\n\n[ext](https://example.com) ![alt](https://img.example/a.png)\n\n### 섹션 하나');
  assert.match(html, /<h2 id="섹션-하나">/);
  assert.match(html, /<h3 id="섹션-하나-1">/);
  assert.match(html, /class="hljs language-python"/);
  assert.match(html, /data-copy-code/);
  assert.match(html, /target="_blank" rel="noopener noreferrer"/);
  assert.match(html, /loading="lazy"/);
  assert.deepEqual(headings.map(h => h.id), ['섹션-하나', '섹션-하나-1']);
});

test('sanitizer strips scripts, inline handlers, javascript: urls, and non-YouTube iframes', () => {
  const out = sanitizeHtml('<p onclick="x()">a</p><script>alert(1)</script><a href="javascript:evil()">b</a><iframe src="https://evil.example"></iframe><iframe src="https://www.youtube.com/embed/x"></iframe>');
  assert.doesNotMatch(out, /<script|onclick|javascript:|evil\.example/);
  assert.match(out, /youtube\.com\/embed/);
});

test('excerpt and reading time are derived from plain text', () => {
  const md = '# 제목\n\n```js\nconst a = 1;\n```\n\n' + '한글 문장입니다. '.repeat(120);
  assert.ok(!excerpt(md, 80).includes('const'));
  assert.ok(excerpt(md, 80).length <= 81);
  assert.ok(readingMinutes(md) >= 1);
});

test('generated index, pages, feed, and template are consistent', () => {
  assert.ok(exists('blog/data/posts.js'), 'run `npm run blog:build:offline` first');
  const context = { window: {} };
  vm.runInNewContext(read('blog/data/posts.js'), context);
  const data = JSON.parse(JSON.stringify(context.window.BLOG_POSTS)); // copy out of the vm realm so deepEqual sees native arrays
  assert.ok(Array.isArray(data.posts) && data.posts.length);
  assert.equal(new Set(data.posts.map(p => p.slug)).size, data.posts.length, 'duplicate slug');
  const dates = data.posts.map(p => new Date(p.date).getTime());
  const sorted = dates.slice().sort((a, b) => b - a);
  assert.deepEqual(dates.join(), sorted.join(), 'posts sorted newest first');
  const feed = read('blog/feed.xml');
  for (const p of data.posts) {
    assert.ok(['velog', 'site'].includes(p.source), p.slug);
    assert.ok(p.title && p.description !== undefined && p.url === `/blog/${encodeURIComponent(p.slug)}/`, p.slug);
    const page = `blog/${p.slug}/index.html`;
    assert.ok(exists(page), page);
    const html = read(page);
    assert.match(html, /generated by scripts\/build-blog\.mjs/);
    assert.match(html, /Content-Security-Policy/);
    assert.match(html, /class="post__content"/);
    assert.ok(html.includes(`<link rel="canonical" href="${p.canonical.replace(/&/g, '&amp;')}">`), `${p.slug} canonical`);
    if (p.source === 'velog') assert.match(html, /velog에서 원문 보기/);
    assert.ok(feed.includes(`<guid isPermaLink="false">${p.source}:${p.slug}</guid>`), `${p.slug} in feed`);
  }
  // every generated directory corresponds to a listed post
  const generated = readdirSync(new URL('../blog/', import.meta.url), { withFileTypes: true })
    .filter(d => d.isDirectory() && !['data', '_posts'].includes(d.name) && exists(`blog/${d.name}/index.html`)).map(d => d.name);
  assert.deepEqual(generated.sort(), data.posts.map(p => p.slug).sort());
});

test('blog pages and the main page share chrome, i18n keys, and have no storage or third-party scripts', () => {
  const list = read('blog/index.html'), tpl = read('scripts/templates/post.html'), js = read('blog/blog.js'), i18n = read('i18n.js'), main = read('index.html');
  for (const html of [list, tpl]) {
    for (const id of ['nav', 'navToggle', 'navLinks', 'navClose', 'themeToggle', 'main']) assert.match(html, new RegExp(`id="${id}"`), id);
    assert.match(html, /class="skip-link"/);
    assert.doesNotMatch(html, /<script[^>]+src="https?:/);
    assert.match(html, /i18n\.js/);
  }
  assert.doesNotMatch(js, /\b(?:localStorage|sessionStorage|fetch\()\b/);
  for (const key of ['nav.blog', 'blog.heading', 'blog.source.site', 'blog.toc', 'blog.viewOnVelog', 'writing.heading']) assert.match(i18n, new RegExp(`'${key.replace('.', '\\.')}'`), key);
  assert.match(main, /href="\.\/blog\/" class="nav__link"/);
  assert.match(main, /id="blogLatest"/);
  assert.ok(main.indexOf('blog/data/posts.js') < main.indexOf('src="./blog/blog.js'));
});
