#!/usr/bin/env node
/* ==========================================================================
   build-blog.mjs — 블로그 빌드 스크립트

   1. velog(@graphy-young) 글을 GraphQL API로 가져와 blog/data/velog.json 에 캐시합니다.
      (네트워크 실패 시 RSS → 기존 캐시 순으로 폴백)
   2. blog/_posts/*.md (이 사이트 전용 글)을 읽습니다.
   3. 두 소스를 합쳐 Markdown → HTML 로 렌더링하고
      - blog/<slug>/index.html   (글 페이지)
      - blog/data/posts.json     (통합 인덱스, JSON)
      - blog/data/posts.js       (통합 인덱스, window.BLOG_POSTS)
      - blog/feed.xml            (RSS 2.0)
      - blog/sitemap.xml
      를 생성합니다.

   사용법:
     node scripts/build-blog.mjs            # velog 동기화 + 빌드
     node scripts/build-blog.mjs --offline  # 네트워크 없이 캐시로만 빌드
     node scripts/build-blog.mjs --check    # 생성물이 최신인지 검사 (CI용)
   ========================================================================== */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync, statSync } from 'node:fs';
import { join, dirname, basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Marked } from 'marked';
import hljs from 'highlight.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BLOG_DIR = join(ROOT, 'blog');
const POSTS_DIR = join(BLOG_DIR, '_posts');
const DATA_DIR = join(BLOG_DIR, 'data');
const TEMPLATE = join(ROOT, 'scripts', 'templates', 'post.html');
const VELOG_CACHE = join(DATA_DIR, 'velog.json');

const SITE = {
  url: 'https://taylorheo.github.io',
  title: '허영대 — 블로그',
  description: '데이터 엔지니어 허영대의 기술 블로그. velog 글과 이 사이트에 직접 올린 글을 함께 모았습니다.',
  author: 'Youngdae Heo',
  velogUser: 'graphy-young',
  velogGraphql: 'https://v3.velog.io/graphql',
  velogRss: 'https://v2.velog.io/rss/@graphy-young',
  reservedSlugs: new Set(['data', '_posts', 'index.html', 'feed.xml', 'sitemap.xml', 'blog.css', 'blog.js'])
};

const args = new Set(process.argv.slice(2));
const OFFLINE = args.has('--offline');
const CHECK = args.has('--check');
const GENERATED_MARK = '<!-- generated by scripts/build-blog.mjs — do not edit; edit blog/_posts or scripts/templates instead -->';

const log = (...m) => console.log('[blog]', ...m);
const warn = (...m) => console.warn('[blog] ⚠', ...m);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

/* -------------------------------------------------------------------------- */
/* Front matter                                                               */
/* -------------------------------------------------------------------------- */
export function parseFrontMatter(raw) {
  const text = raw.replace(/^\uFEFF/, '');
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { meta: {}, body: text };
  const meta = {};
  const lines = m[1].split(/\r?\n/);
  let listKey = null;
  for (const line of lines) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const item = line.match(/^\s*-\s+(.*)$/);
    if (item && listKey) { meta[listKey].push(unquote(item[1])); continue; }
    const kv = line.match(/^([A-Za-z_][\w-]*)\s*:\s*(.*)$/);
    if (!kv) continue;
    const [, key, valueRaw] = kv;
    const value = valueRaw.trim();
    if (value === '') { meta[key] = []; listKey = key; continue; }
    listKey = null;
    if (value.startsWith('[') && value.endsWith(']')) {
      meta[key] = value.slice(1, -1).split(',').map(v => unquote(v.trim())).filter(Boolean);
    } else if (value === 'true' || value === 'false') {
      meta[key] = value === 'true';
    } else {
      meta[key] = unquote(value);
    }
  }
  return { meta, body: m[2] };
}
function unquote(v) {
  const s = String(v).trim();
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) return s.slice(1, -1);
  return s;
}

/* -------------------------------------------------------------------------- */
/* Slug / text helpers                                                        */
/* -------------------------------------------------------------------------- */
export function slugify(input) {
  return String(input ?? '')
    .normalize('NFC')
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, '-')
    .replace(/[^\p{L}\p{N}-]+/gu, '')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');
}
function safeDirName(slug) {
  // velog slug은 원형을 유지하되 파일시스템/URL에 위험한 문자만 제거
  return decodeURIComponentSafe(slug).normalize('NFC').replace(/[\/\\?#%<>:"|*\s]+/g, '-').replace(/^\.+/, '').replace(/-{2,}/g, '-').replace(/^-+|-+$/g, '');
}
function decodeURIComponentSafe(s) { try { return decodeURIComponent(s); } catch { return s; } }

export function stripMarkdown(md) {
  return String(md ?? '')
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`[^`]*`/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/<[^>]+>/g, ' ')
    .replace(/^[#>\-*+\d.\s|]+/gm, '')
    .replace(/[*_~]+/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}
export function excerpt(md, max = 160) {
  const text = stripMarkdown(md);
  if (text.length <= max) return text;
  return text.slice(0, max).replace(/\s+\S*$/, '') + '…';
}
export function readingMinutes(md) {
  const text = stripMarkdown(md);
  const cjk = (text.match(/[\u3131-\uD79D\u4E00-\u9FFF\u3040-\u30FF]/g) || []).length;
  const words = text.replace(/[\u3131-\uD79D\u4E00-\u9FFF\u3040-\u30FF]/g, ' ').split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(cjk / 500 + words / 200));
}
const fmtDate = (iso, lang = 'ko') => {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  const ymd = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d); // YYYY-MM-DD
  return lang === 'en' ? ymd : ymd.replace(/-/g, '.');
};
const plainText = html => String(html ?? '').replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\s+/g, ' ').trim();

/* -------------------------------------------------------------------------- */
/* velog fetch                                                                */
/* -------------------------------------------------------------------------- */
async function gql(query, variables) {
  const res = await fetch(SITE.velogGraphql, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'user-agent': 'taylorheo.github.io blog sync' },
    body: JSON.stringify({ query, variables }),
    signal: AbortSignal.timeout(20000)
  });
  if (!res.ok) throw new Error(`velog GraphQL HTTP ${res.status}`);
  const json = await res.json();
  if (json.errors?.length) throw new Error('velog GraphQL: ' + json.errors.map(e => e.message).join('; '));
  return json.data;
}

async function fetchVelogViaGraphql() {
  const list = [];
  let cursor = null;
  for (let page = 0; page < 50; page++) {
    const data = await gql(`query Posts($input: GetPostsInput!) {
      posts(input: $input) { id title short_description thumbnail url_slug released_at updated_at tags is_private }
    }`, { input: { username: SITE.velogUser, limit: 20, cursor } });
    const batch = data?.posts ?? [];
    list.push(...batch.filter(p => !p.is_private));
    if (batch.length < 20) break;
    cursor = batch[batch.length - 1].id;
  }
  const posts = [];
  for (const p of list) {
    const data = await gql(`query ReadPost($input: ReadPostInput!) {
      post(input: $input) { id title body url_slug released_at updated_at tags thumbnail short_description series { name url_slug } }
    }`, { input: { username: SITE.velogUser, url_slug: p.url_slug } });
    const full = data?.post;
    if (!full?.body) { warn('본문 없음, 건너뜀:', p.url_slug); continue; }
    posts.push({
      id: full.id,
      title: full.title,
      slug: full.url_slug,
      url: `https://velog.io/@${SITE.velogUser}/${encodeURIComponent(full.url_slug)}`,
      body: full.body,
      description: full.short_description || '',
      tags: full.tags || [],
      thumbnail: full.thumbnail || null,
      series: full.series?.name || null,
      date: full.released_at,
      updated: full.updated_at
    });
  }
  return posts;
}

async function fetchVelogViaRss() {
  const res = await fetch(SITE.velogRss, { signal: AbortSignal.timeout(20000) });
  if (!res.ok) throw new Error(`velog RSS HTTP ${res.status}`);
  const xml = await res.text();
  const items = [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(m => m[1]);
  const pick = (block, tag) => {
    const m = block.match(new RegExp(`<${tag}>(?:<!\\[CDATA\\[)?([\\s\\S]*?)(?:\\]\\]>)?<\\/${tag}>`));
    return m ? m[1].trim() : '';
  };
  return items.map(block => {
    const link = pick(block, 'link');
    const slug = decodeURIComponentSafe(link.split('/').pop() || '');
    return {
      id: pick(block, 'guid') || link,
      title: pick(block, 'title'),
      slug,
      url: link,
      body: null,
      html: pick(block, 'description'),
      description: '',
      tags: [],
      thumbnail: null,
      series: null,
      date: new Date(pick(block, 'pubDate')).toISOString(),
      updated: null
    };
  });
}

async function loadVelogPosts() {
  const cached = existsSync(VELOG_CACHE) ? JSON.parse(readFileSync(VELOG_CACHE, 'utf8')) : null;
  if (OFFLINE) {
    log(`offline 모드: velog 캐시 ${cached?.posts?.length ?? 0}건 사용`);
    return cached?.posts ?? [];
  }
  try {
    const posts = await fetchVelogViaGraphql();
    log(`velog GraphQL: ${posts.length}건 수집`);
    mkdirSync(DATA_DIR, { recursive: true });
    writeFileSync(VELOG_CACHE, JSON.stringify({ source: 'graphql', user: SITE.velogUser, posts }, null, 2) + '\n');
    return posts;
  } catch (e) {
    warn('velog GraphQL 실패:', e.message);
  }
  try {
    const posts = await fetchVelogViaRss();
    log(`velog RSS 폴백: ${posts.length}건 수집 (본문은 RSS HTML)`);
    // RSS 결과는 캐시보다 정보가 적으므로, 캐시가 있으면 캐시 본문을 우선 사용
    if (cached?.posts?.length) {
      const bySlug = new Map(cached.posts.map(p => [p.slug, p]));
      return posts.map(p => bySlug.get(p.slug) ?? p).concat(cached.posts.filter(p => !posts.some(q => q.slug === p.slug)));
    }
    return posts;
  } catch (e) {
    warn('velog RSS 실패:', e.message);
  }
  if (cached?.posts) { warn(`네트워크 실패 — 캐시 ${cached.posts.length}건 사용`); return cached.posts; }
  warn('velog 글을 가져오지 못했고 캐시도 없습니다. velog 글 없이 빌드합니다.');
  return [];
}

/* -------------------------------------------------------------------------- */
/* Markdown rendering                                                          */
/* -------------------------------------------------------------------------- */
function createRenderer() {
  const headings = [];
  const used = new Map();
  const uniqueId = base => {
    const id = slugify(base) || 'section';
    const n = used.get(id) ?? 0;
    used.set(id, n + 1);
    return n ? `${id}-${n}` : id;
  };
  const renderer = {
    heading({ tokens, depth }) {
      const html = this.parser.parseInline(tokens);
      const text = plainText(html);
      const id = uniqueId(text);
      if (depth >= 2 && depth <= 3) headings.push({ depth, id, text });
      return `<h${depth} id="${esc(id)}"><a class="post__anchor" href="#${esc(id)}" aria-label="${esc(text)} 섹션 링크">#</a>${html}</h${depth}>\n`;
    },
    code({ text, lang }) {
      const language = (lang || '').trim().split(/\s+/)[0].toLowerCase();
      let body, cls = '';
      if (language && hljs.getLanguage(language)) {
        body = hljs.highlight(text, { language, ignoreIllegals: true }).value;
        cls = ` class="hljs language-${esc(language)}"`;
      } else if (text.length < 20000) {
        const auto = hljs.highlightAuto(text);
        body = auto.value; cls = ` class="hljs${auto.language ? ` language-${esc(auto.language)}` : ''}"`;
      } else {
        body = esc(text); cls = ' class="hljs"';
      }
      const label = language ? `<span class="post__code-lang">${esc(language)}</span>` : '';
      return `<div class="post__code">${label}<button type="button" class="post__copy" data-copy-code aria-label="코드 복사">Copy</button><pre><code${cls}>${body}</code></pre></div>\n`;
    },
    image({ href, title, text }) {
      const t = title ? ` title="${esc(title)}"` : '';
      return `<img src="${esc(href)}" alt="${esc(text || '')}"${t} loading="lazy" decoding="async">`;
    },
    link({ href, title, tokens }) {
      const html = this.parser.parseInline(tokens);
      const external = /^https?:\/\//i.test(href) && !href.startsWith(SITE.url);
      const t = title ? ` title="${esc(title)}"` : '';
      const ext = external ? ' target="_blank" rel="noopener noreferrer"' : '';
      return `<a href="${esc(href)}"${t}${ext}>${html}</a>`;
    },
    table({ header, rows }) {
      const cell = (c, tag) => `<${tag}${c.align ? ` style="text-align:${c.align}"` : ''}>${this.parser.parseInline(c.tokens)}</${tag}>`;
      const head = `<thead><tr>${header.map(c => cell(c, 'th')).join('')}</tr></thead>`;
      const body = rows.map(r => `<tr>${r.map(c => cell(c, 'td')).join('')}</tr>`).join('');
      return `<div class="post__table"><table>${head}<tbody>${body}</tbody></table></div>\n`;
    }
  };
  return { renderer, headings };
}

export function sanitizeHtml(html) {
  return String(html)
    .replace(/<script\b[\s\S]*?<\/script>/gi, '')
    .replace(/<(iframe)\b([^>]*)>/gi, (m, tag, attrs) => /src=["']https:\/\/(www\.)?(youtube\.com|youtube-nocookie\.com)\//i.test(attrs) ? m : '')
    .replace(/\son[a-z]+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, '')
    .replace(/\s(href|src)\s*=\s*(["']?)\s*javascript:[^"'\s>]*\2/gi, ' $1=$2#$2');
}

export function renderMarkdown(md) {
  const { renderer, headings } = createRenderer();
  const instance = new Marked({ gfm: true, breaks: true });
  instance.use({ renderer });
  const html = sanitizeHtml(instance.parse(md ?? ''));
  return { html, headings };
}

/* -------------------------------------------------------------------------- */
/* Local markdown posts                                                       */
/* -------------------------------------------------------------------------- */
function loadLocalPosts() {
  if (!existsSync(POSTS_DIR)) return [];
  const files = readdirSync(POSTS_DIR).filter(f => /\.(md|markdown)$/i.test(f) && !f.startsWith('_') && f.toLowerCase() !== 'readme.md').sort();
  const posts = [];
  for (const file of files) {
    const raw = readFileSync(join(POSTS_DIR, file), 'utf8');
    const { meta, body } = parseFrontMatter(raw);
    if (meta.draft === true) { log('draft 건너뜀:', file); continue; }
    const base = basename(file).replace(/\.(md|markdown)$/i, '');
    const dateFromName = base.match(/^(\d{4}-\d{2}-\d{2})[-_]?/);
    const rawDate = meta.date ?? dateFromName?.[1];
    if (!rawDate) throw new Error(`${file}: front matter에 date가 없고 파일명에도 날짜(YYYY-MM-DD-)가 없습니다.`);
    const date = new Date(rawDate);
    if (Number.isNaN(date.getTime())) throw new Error(`${file}: date 형식을 해석할 수 없습니다 (${rawDate}).`);
    const titleFromBody = body.match(/^#\s+(.+)$/m)?.[1];
    const title = meta.title ?? titleFromBody;
    if (!title) throw new Error(`${file}: front matter에 title이 없고 본문에 H1도 없습니다.`);
    const slug = slugify(meta.slug ?? (dateFromName ? base.slice(dateFromName[0].length) : base));
    if (!slug) throw new Error(`${file}: slug를 만들 수 없습니다. front matter에 slug를 지정하세요.`);
    let content = body;
    if (!meta.title && titleFromBody) content = body.replace(/^#\s+.+$\n?/m, '');
    const tags = Array.isArray(meta.tags) ? meta.tags : typeof meta.tags === 'string' ? meta.tags.split(',').map(s => s.trim()).filter(Boolean) : [];
    posts.push({
      source: 'site', file, slug, title, body: content,
      description: meta.description ?? meta.summary ?? '',
      tags, thumbnail: meta.thumbnail ?? meta.image ?? null, series: meta.series ?? null,
      date: date.toISOString(), updated: meta.updated ? new Date(meta.updated).toISOString() : null,
      lang: meta.lang === 'en' ? 'en' : 'ko', canonical: meta.canonical ?? null
    });
  }
  return posts;
}

/* -------------------------------------------------------------------------- */
/* Build                                                                      */
/* -------------------------------------------------------------------------- */
function renderTemplate(tpl, vars) {
  return tpl.replace(/\{\{(\w+)\}\}/g, (_, k) => (k in vars ? String(vars[k]) : ''));
}

function listGeneratedDirs() {
  if (!existsSync(BLOG_DIR)) return [];
  return readdirSync(BLOG_DIR).filter(name => {
    const p = join(BLOG_DIR, name, 'index.html');
    if (!statSync(join(BLOG_DIR, name)).isDirectory() || !existsSync(p)) return false;
    return readFileSync(p, 'utf8').includes(GENERATED_MARK);
  });
}

export async function build() {
  const template = readFileSync(TEMPLATE, 'utf8');
  const velog = await loadVelogPosts();
  const local = loadLocalPosts();

  const all = [];
  const seen = new Map();
  for (const p of velog) {
    const slug = safeDirName(p.slug);
    if (!slug || SITE.reservedSlugs.has(slug)) { warn('예약된 slug, 건너뜀:', p.slug); continue; }
    seen.set(slug, 'velog');
    all.push({ ...p, source: 'velog', slug, lang: 'ko', canonical: p.url });
  }
  for (const p of local) {
    if (SITE.reservedSlugs.has(p.slug)) throw new Error(`${p.file}: '${p.slug}'는 예약된 경로입니다. 다른 slug를 지정하세요.`);
    if (seen.has(p.slug)) throw new Error(`${p.file}: slug '${p.slug}'가 ${seen.get(p.slug)} 글과 겹칩니다. front matter의 slug를 바꿔주세요.`);
    seen.set(p.slug, 'site');
    all.push(p);
  }
  all.sort((a, b) => new Date(b.date) - new Date(a.date));

  // 렌더링
  const rendered = all.map(p => {
    let html, headings = [];
    if (p.body != null) ({ html, headings } = renderMarkdown(p.body));
    else { html = sanitizeHtml(p.html || ''); }
    const plain = p.body != null ? stripMarkdown(p.body) : stripMarkdown(html);
    return {
      ...p, html, headings,
      description: p.description || excerpt(p.body ?? plain, 160),
      readingMinutes: p.body != null ? readingMinutes(p.body) : Math.max(1, Math.round(plain.length / 500)),
      pagePath: `/blog/${encodeURIComponent(p.slug)}/`
    };
  });

  const index = rendered.map(p => ({
    slug: p.slug, source: p.source, title: p.title, description: p.description,
    date: p.date, updated: p.updated ?? null, tags: p.tags ?? [], series: p.series ?? null,
    thumbnail: p.thumbnail ?? null, readingMinutes: p.readingMinutes, lang: p.lang,
    url: p.pagePath, canonical: p.canonical ?? `${SITE.url}${p.pagePath}`
  }));

  const outputs = new Map();
  const tagCounts = {};
  for (const p of index) for (const t of p.tags) tagCounts[t] = (tagCounts[t] || 0) + 1;
  const indexJson = { site: SITE.url, count: index.length, tags: tagCounts, posts: index };
  outputs.set(join(DATA_DIR, 'posts.json'), JSON.stringify(indexJson, null, 2) + '\n');
  outputs.set(join(DATA_DIR, 'posts.js'), `/* generated by scripts/build-blog.mjs */\nwindow.BLOG_POSTS = ${JSON.stringify(indexJson)};\n`);

  rendered.forEach((p, i) => {
    const prev = rendered[i + 1], next = rendered[i - 1];
    const toc = p.headings.length >= 2
      ? `<nav class="post__toc" aria-labelledby="tocHeading"><p class="post__toc-heading" id="tocHeading" data-i18n="blog.toc">목차</p><ol>${p.headings.map(h => `<li class="post__toc-item post__toc-item--${h.depth}"><a href="#${esc(h.id)}">${esc(h.text)}</a></li>`).join('')}</ol></nav>`
      : '';
    const tags = p.tags?.length ? `<ul class="post__tags" role="list">${p.tags.map(t => `<li><a class="e-chip" href="../?tag=${encodeURIComponent(t)}">${esc(t)}</a></li>`).join('')}</ul>` : '';
    const sourceBadge = p.source === 'velog'
      ? `<span class="post__source post__source--velog">velog</span>`
      : `<span class="post__source post__source--site" data-i18n="blog.source.site">이 사이트</span>`;
    const canonicalNote = p.source === 'velog'
      ? `<p class="post__origin"><span data-i18n="blog.originVelog">이 글은 velog에 처음 게시되었습니다.</span> <a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer"><span data-i18n="blog.viewOnVelog">velog에서 원문 보기</span> ↗</a></p>`
      : '';
    const navLink = (post, cls, label) => post
      ? `<a class="post__nav-link ${cls}" href="../${encodeURIComponent(post.slug)}/"><span class="post__nav-label" data-i18n="${label}">${label === 'blog.prev' ? '이전 글' : '다음 글'}</span><span class="post__nav-title">${esc(post.title)}</span></a>`
      : `<span class="post__nav-link ${cls} post__nav-link--empty"></span>`;
    const bodyHasThumb = p.thumbnail && (p.body ?? p.html ?? '').includes(p.thumbnail);
    const thumb = p.thumbnail && !bodyHasThumb ? `<figure class="post__hero"><img src="${esc(p.thumbnail)}" alt="" loading="eager" decoding="async"></figure>` : '';
    const html = renderTemplate(template, {
      GENERATED_MARK,
      root: '../../',
      lang: p.lang,
      title: esc(p.title),
      pageTitle: esc(`${p.title} — 허영대 블로그`),
      description: esc(p.description),
      canonical: esc(p.canonical ?? `${SITE.url}${p.pagePath}`),
      pageUrl: esc(`${SITE.url}${p.pagePath}`),
      ogImage: esc(p.thumbnail || `${SITE.url}/og-image.png`),
      datetime: esc(p.date),
      dateKo: fmtDate(p.date, 'ko'),
      dateEn: fmtDate(p.date, 'en'),
      updatedRow: p.updated && fmtDate(p.updated) !== fmtDate(p.date) ? `<span class="post__meta-sep" aria-hidden="true">·</span><span><span data-i18n="blog.updated">수정</span> <time datetime="${esc(p.updated)}" data-date-ko="${fmtDate(p.updated, 'ko')}" data-date-en="${fmtDate(p.updated, 'en')}">${fmtDate(p.updated, 'ko')}</time></span>` : '',
      readingMinutes: p.readingMinutes,
      sourceBadge, tags, toc, canonicalNote, thumb,
      content: p.html,
      prevLink: navLink(prev, 'post__nav-link--prev', 'blog.prev'),
      nextLink: navLink(next, 'post__nav-link--next', 'blog.next'),
      jsonLd: JSON.stringify({
        '@context': 'https://schema.org', '@type': 'BlogPosting', headline: p.title, description: p.description,
        datePublished: p.date, dateModified: p.updated || p.date, inLanguage: p.lang,
        author: { '@type': 'Person', name: SITE.author, url: SITE.url }, image: p.thumbnail || undefined,
        mainEntityOfPage: `${SITE.url}${p.pagePath}`, url: p.canonical, keywords: p.tags?.join(', ') || undefined
      }).replace(/</g, '\\u003c')
    });
    outputs.set(join(BLOG_DIR, p.slug, 'index.html'), html);
  });

  // RSS feed
  const feedItems = rendered.map(p => `    <item>
      <title><![CDATA[${p.title}]]></title>
      <link>${esc(SITE.url + p.pagePath)}</link>
      <guid isPermaLink="false">${esc(`${p.source}:${p.slug}`)}</guid>
      <pubDate>${new Date(p.date).toUTCString()}</pubDate>
      ${p.tags.map(t => `<category><![CDATA[${t}]]></category>`).join('')}
      <description><![CDATA[${p.description}]]></description>
      <content:encoded><![CDATA[${p.html.replace(/\]\]>/g, ']]]]><![CDATA[>')}]]></content:encoded>
    </item>`).join('\n');
  outputs.set(join(BLOG_DIR, 'feed.xml'), `<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>${esc(SITE.title)}</title>
    <link>${SITE.url}/blog/</link>
    <description>${esc(SITE.description)}</description>
    <language>ko</language>
    <lastBuildDate>${new Date(rendered[0]?.date ?? Date.now()).toUTCString()}</lastBuildDate>
    <atom:link href="${SITE.url}/blog/feed.xml" rel="self" type="application/rss+xml"/>
${feedItems}
  </channel>
</rss>
`);

  // Sitemap
  outputs.set(join(BLOG_DIR, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${SITE.url}/</loc></url>
  <url><loc>${SITE.url}/blog/</loc>${rendered[0] ? `<lastmod>${rendered[0].date.slice(0, 10)}</lastmod>` : ''}</url>
${rendered.map(p => `  <url><loc>${esc(SITE.url + p.pagePath)}</loc><lastmod>${(p.updated || p.date).slice(0, 10)}</lastmod></url>`).join('\n')}
</urlset>
`);

  // 오래된 생성물 제거 대상
  const keep = new Set(rendered.map(p => p.slug));
  const stale = listGeneratedDirs().filter(d => !keep.has(d));

  if (CHECK) {
    const diffs = [];
    for (const [file, content] of outputs) {
      if (!existsSync(file) || readFileSync(file, 'utf8') !== content) diffs.push(file.replace(ROOT + '/', ''));
    }
    diffs.push(...stale.map(d => `blog/${d}/ (stale)`));
    if (diffs.length) { console.error('[blog] 생성물이 최신이 아닙니다:\n  ' + diffs.join('\n  ')); process.exit(1); }
    log('생성물이 최신입니다.');
    return { posts: index };
  }

  for (const [file, content] of outputs) { mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, content); }
  for (const d of stale) { rmSync(join(BLOG_DIR, d), { recursive: true, force: true }); log('오래된 글 페이지 삭제:', d); }
  log(`빌드 완료: velog ${velog.length}건 + 사이트 ${local.length}건 = ${index.length}건`);
  return { posts: index };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  build().catch(e => { console.error('[blog] 빌드 실패:', e.message); process.exit(1); });
}
